import { isClaimed } from "../message-gate.js";
// ─── Atmospheric Auto-Styler (!aesthetic) ────────────────────────────────────
// Transforms any text into:
//  • Poetic Japanese translation (Kanji + Furigana in parentheses)
//  • Unicode decorative font variants (bold, script, small-caps)
//  • Smart mood-aware hashtags generated by Gemini

import { Client, Message } from "discord.js";
import { generateWithFallback } from "@workspace/integrations-gemini-ai";

// ── Unicode font helpers ──────────────────────────────────────────────────────

function toBold(text: string): string {
  return [...text].map(c => {
    const n = c.charCodeAt(0);
    if (n >= 65 && n <= 90)  return String.fromCodePoint(0x1D400 + n - 65); // A-Z
    if (n >= 97 && n <= 122) return String.fromCodePoint(0x1D41A + n - 97); // a-z
    if (n >= 48 && n <= 57)  return String.fromCodePoint(0x1D7CE + n - 48); // 0-9
    return c;
  }).join("");
}

function toScript(text: string): string {
  // Mathematical script has exceptions for some letters
  const exc: Record<string, string> = {
    B:"ℬ", E:"ℰ", F:"ℱ", H:"ℋ", I:"ℐ", L:"ℒ", M:"ℳ", R:"ℛ",
    e:"ℯ", g:"ℊ", o:"ℴ",
  };
  return [...text].map(c => {
    if (exc[c]) return exc[c];
    const n = c.charCodeAt(0);
    if (n >= 65 && n <= 90)  return String.fromCodePoint(0x1D49C + n - 65);
    if (n >= 97 && n <= 122) return String.fromCodePoint(0x1D4B6 + n - 97);
    return c;
  }).join("");
}

function toSmallCaps(text: string): string {
  const map: Record<string, string> = {
    a:"ᴀ", b:"ʙ", c:"ᴄ", d:"ᴅ", e:"ᴇ", f:"ꜰ", g:"ɢ", h:"ʜ", i:"ɪ", j:"ᴊ",
    k:"ᴋ", l:"ʟ", m:"ᴍ", n:"ɴ", o:"ᴏ", p:"ᴘ", q:"Q", r:"ʀ", s:"ꜱ", t:"ᴛ",
    u:"ᴜ", v:"ᴠ", w:"ᴡ", x:"x", y:"ʏ", z:"ᴢ",
  };
  return [...text.toLowerCase()].map(c => map[c] ?? c).join("");
}

function toWide(text: string): string {
  return [...text].map(c => {
    const n = c.charCodeAt(0);
    if (n >= 33 && n <= 126) return String.fromCodePoint(0xFF01 + n - 33);
    return c;
  }).join("");
}

// ── Gemini transformation ─────────────────────────────────────────────────────
interface AestheticResult {
  japanese:   string; // poetic Japanese translation
  romaji:     string; // romanised reading
  meaning:    string; // one-line English interpretation
  tags:       string[]; // 6-10 mood tags, no # symbol, no spaces
}

async function transformAesthetic(text: string): Promise<AestheticResult> {
  const prompt =
    `You are an aesthetic content creator.\n` +
    `Transform this text: "${text}"\n\n` +
    `Return ONLY a valid JSON object — no markdown, no explanation:\n` +
    `{\n` +
    `  "japanese": "poetic Japanese translation using natural kanji/hiragana/katakana. For each kanji include the furigana reading in parentheses directly after it, e.g. 夜(よる)の光(ひかり). Make it atmospheric and poetic.",\n` +
    `  "romaji": "romanised reading of the Japanese above",\n` +
    `  "meaning": "one English sentence capturing the poetic meaning",\n` +
    `  "tags": ["word1", "word2"] — 6 to 10 lowercase, no spaces, no # symbol, mood/theme/aesthetic tags\n` +
    `}`;

  const rawText = await generateWithFallback({
    contents: [{ role: "user", parts: [{ text: prompt }] }],
    maxOutputTokens: 1024,
  });

  const raw = rawText?.trim() ?? "";
  const m   = raw.match(/\{[\s\S]*\}/);
  if (!m) throw new Error("No JSON returned");
  const parsed = JSON.parse(m[0]);

  if (typeof parsed.japanese !== "string" || !Array.isArray(parsed.tags)) {
    throw new Error("Unexpected JSON shape");
  }

  return {
    japanese: parsed.japanese,
    romaji:   typeof parsed.romaji  === "string" ? parsed.romaji  : "",
    meaning:  typeof parsed.meaning === "string" ? parsed.meaning : "",
    tags:     (parsed.tags as string[]).slice(0, 10),
  };
}

// ── Register ──────────────────────────────────────────────────────────────────
export function registerAesthetic(client: Client, PREFIX: string): void {
  client.on("messageCreate", async (message: Message) => {
    if (message.author.bot) return;
    if (!(await isClaimed(message.id))) return;

    const content = message.content.trim();
    const cmd     = `${PREFIX}aesthetic`;
    if (!content.toLowerCase().startsWith(cmd)) return;

    const text = content.slice(cmd.length).trim();

    if (!text) {
      await message.reply(
        `**Usage:** \`!aesthetic <your text here>\`\n` +
        `**Example:** \`!aesthetic I love coding at midnight\``,
      );
      return;
    }

    if (text.length > 300) {
      await message.reply("⚠️ Text too long — keep it under 300 characters.");
      return;
    }

    await (message.channel as any).sendTyping();

    try {
      const result = await transformAesthetic(text);

      const boldText    = toBold(text);
      const scriptText  = toScript(text);
      const smallCaps   = toSmallCaps(text);
      const wideText    = toWide(text);
      const hashtagLine = result.tags.map(t => `#${t.replace(/\s+/g, "")}`).join("  ");

      const lines = [
        `╭────────────── ✦ aesthetic ✦ ──────────────╮`,
        ``,
        `**Original**`,
        `> ${text}`,
        ``,
        `**𝐁𝐨𝐥𝐝**`,
        `> ${boldText}`,
        ``,
        `**𝒮𝒸𝓇𝒾𝓅𝓉**`,
        `> ${scriptText}`,
        ``,
        `**ꜱᴍᴀʟʟ ᴄᴀᴘꜱ**`,
        `> ${smallCaps}`,
        ``,
        `**ｆｕｌｌｗｉｄｔｈ**`,
        `> ${wideText}`,
        ``,
        `**日本語 🌸**`,
        `> ${result.japanese}`,
        result.romaji  ? `> *${result.romaji}*`  : "",
        result.meaning ? `> "${result.meaning}"` : "",
        ``,
        `**Tags**`,
        `\`\`\``,
        hashtagLine,
        `\`\`\``,
        `╰──────────────────────────────────────────╯`,
      ].filter(l => l !== undefined);

      const output = lines.join("\n");

      if (output.length > 1990) {
        // Split at the Tags section if too long
        const splitAt = output.indexOf("**Tags**");
        if (splitAt > 0) {
          await message.reply(output.slice(0, splitAt).trim());
          await (message.channel as any).send(output.slice(splitAt));
        } else {
          await message.reply(output.slice(0, 1990) + "…");
        }
      } else {
        await message.reply(output);
      }

    } catch (err) {
      console.error("[Aesthetic] Error:", err);
      await message.reply("😅 Something went wrong during conversion — please try again!");
    }
  });
}
